@startuml pdfpage_builder
hide empty members
class pdfpage_builder {
	+pdfpage_builder()
	+to_pdfpage() : PDFReader::PDFPage
	+set_media_box(media_box : const RectangleData&)
	+set_contents(page_content : PDFContents^)
	-m_page : PDFPage
}
pdfpage_builder --> PDFPage

class PDFPage {
	[[PDFPage.class.pu]]
}
@enduml
