@startuml pdfpage_builder
partition "pdfpage_builder()" {
start
stop
}
@enduml

@startuml toPDFPage
partition "toPDFPage()" {
start
	:return m_page;
stop
}
@enduml

@startuml SetMediaBox
partition "SetMediaBox(media_box : const RectangleData&)" {
start
	:m_page.MediaBox = media_box;
stop
}
@enduml

@startuml SetContents
partition "SetContents(page_content : const PDFContents&)" {
start
	:m_page.Contents = page_content;
stop
}
@enduml
