@startuml document_reader
partition "document_reader(inout stream : ipdfstream&)" {
start
	:m_stream = stream;
	:m_trailer_dictionary = m_stream.take_footer();
stop
}
@enduml

@startuml get_pages
partition "get_pages()" {
start
	:root_dictionary = m_trailer_dictionary.at("Root");
	:page_tree_root = root_dictionary.at("Pages");
	:this_page_tree_parser = page_tree_parser(m_stream, page_tree_root);
	:return this_page_tree_parser.get_pages();
stop
}
@enduml
