@startuml document_error
hide empty members
namespace pdfparser {
abstract document_error {
	-m_message : shared_ptr<char[]>

	+document_error(in message : std::string_view)

	+what() const noexcept final : const char* 
}
document_error --|> std::exception

abstract position_indicatable_error {
	-m_position : std::streampos

	+position_indicatable_error(in position : std::streampos, in message : std::string_view)

	+tell_position() : std::streampos
}
position_indicatable_error --|> document_error
}
@enduml
