@startuml document_reader
hide empty members
namespace pdfparser {
class document_reader<InputStreamT> {
	-m_object_parser      : object_parser<InputStreamT>
	-m_trailer_dictionary : dictionary_object
	-m_object_pool        : object_pool<InputStreamT>
	-m_page_tree_parser   : page_tree_parser<InputStreamT>

	+document_reader(in stream : InputStreamT&&)
	+document_reader(const InputStreamT&&) = delete
	+document_reader(InputStreamT&)        = delete
	+get_pages() : List<PDFPage>
}
document_reader --> pages_parser
document_reader ..> "0..*" PDFPage

class pages_parser<InputStreamT> {
	[[pages_parser.class.pu]]
}
class PDFPage {
	[[data_types.class.pu]]
}
@enduml
