@startuml document_error_what
partition "what()" {
start
	:return m_message.get();
stop
}
@enduml

@startuml position_indicatable_error_tell_position
partition "tell_position()" {
start
	:return m_position;
stop
}
@enduml

@startuml position_indicatable_error
partition "position_indicatable_error(in position : std::streampos, in message : std::string_view)" {
start
	:m_position = position;

	:message_stream : stringstream;
	:message_stream << "at " << m_position << " byte\\n";
	:content = stringstream;
	:content << message;
	:content << "\\n\\n" << '(' << typeid(*this).name() << ')';

	:line : std::string;
	while (std::getline(content, line)) is (y)
		:message_stream << "  " << line << '\\n';
	endwhile

	:document_error(message_stream.str());
stop
}
@enduml
