@startuml document_reader
hide empty members
namespace pdfparser {
class document_reader<InputStreamT> {
	-m_stream_parser      : document_parser<InputStreamT>
	-m_trailer_dictionary : dictionary_object
	-m_object_pool        : object_pool<InputStreamT>

	+document_reader(in stream : InputStreamT&&)
	+document_reader(const InputStreamT&&) = delete
	+document_reader(InputStreamT&)        = delete
	+GetPages() : List<PDFPage>
	+GetPage(page_dictionary : const dictionary_object&) : PDFPage
	+GetContents(contents_builder : pdfcontents_builder&, content_stream : string_view) : PDFContents
	-GetPages(page_node : const dictionary_object&, inherited_attributes : const dictionary_object&) : List<PDFPage>
}
document_reader --> document_parser
document_reader --> dictionary_object 
document_reader --> object_pool
document_reader --> "0..*" PDFPage

class document_parser<InputStreamT> {
	[[document_parser.class.pu]]
}
class object_pool {
	[[object_pool.class.pu]]
}
class dictionary_object {
	[[object_types.class.pu]]
}
class PDFPage {
	[[data_types.class.pu]]
}
@enduml
