@startuml object_parser
hide empty members
namespace pdfparser {
enum parse_error::error_code <<Enumeration>> {
	<<Const>>
	+{static} xref_entry_keyword_invalid                      : int = 0
	+{static} literal_string_lack_of_right_parenthesis        : int = 1
	+{static} array_lack_of_right_square_bracket              : int = 2
	+{static} array_invalid_element                           : int = 3
	+{static} hexadecimal_string_non_hexadecimal_digit_found  : int = 4
	+{static} hexadecimal_string_lack_of_greater_than_sign    : int = 5
	+{static} dictionary_lack_of_double_greater_than_sign     : int = 6
	+{static} dictionary_invalid_key                          : int = 7
	+{static} dictionary_invalid_value                        : int = 8
	+{static} stream_dictionary_absence_of_Length_entry       : int = 9
	+{static} stream_data_is_shorter_than_Length              : int = 10
	+{static} indirect_object_is_inconsistent_with_xref_table : int = 11
}
class parse_error {
	+enum error_code
	-m_error_code : const error_code

	+parse_error(in er_code : error_code)
	+code() : error_code
}
parse_error --|> std::runtime_error
parse_error --> "1" parse_error::error_code
}
@enduml
