@startuml pdfcontents_builder
hide empty members
abstract pdfcontents_builder {
	+concat_CTM(concat_matrix : const AffineMatrix&) : void
	+set_line_dash_pattern(line_dash_pattern : line_style::dash_pattern_type) : void
	+set_flatness(flatness : double) : void
	+set_line_join_style(line_join_style : line_style::join_type) : void
	+set_line_cap_style(line_cap_style : line_style::cap_type) : void
	+set_miter_limit(miter_limit : double) : void
	+set_line_width(line_width : double) : void
	+set_fill_color(fill_color : color) : void
	+set_stroke_color(stroke_color : color) : void
	+set_character_spacing(character_spacing : double) : void
	+set_leading(leading : double) : void
	+set_text_rendering_mode(text_rendering_mode : text_style::rendering_mode) : void
	+set_text_rise(text_rise : double) : void
	+set_word_spacing(word_spacing : double) : void
	+set_horizontal_scaling(horizontal_scaling : double) : void

	+set_text_matrices(next_line_x : double, next_line_y : double) : void
	+concat_text_matrices(next_line_offset_x : double, next_line_offset_y : double) : void
	+move_to_next_line() : void
	+begin_text() : void
	+end_text()   : void

	-m_graphics_states : graphics_state_stack

	' These matrices are ambiguously represented in PDF 1.0, but are clearly defined in PDF 1.7.
	-m_text_matrix : AffineMatrix
	-m_text_line_matrix : AffineMatrix
}
pdfcontents_builder ..> line_style
pdfcontents_builder ..> text_style

annotation line_style <<(N, yellow) namespace>> {
	[[line_style.class.pu]]
}
annotation text_style <<(N, yellow) namespace>> {
	[[text_style.class.pu]]
}
abstract graphics_state_stack {
	[[graphics_state_stack.class.pu]]
}
@enduml
