@startuml at
partition "at(in object_number : object_t, in generation_number : generation_t)" {
start
	:object_it = find(object_t, generation_t);
	if (object_it != end()) then (y)
		:return *object_it;
		stop
	else
		:throw std::out_of_range("unordered_map");
		stop
	endif
}
@enduml

@startuml find
partition "find(in object_number : object_t, in generation_number : generation_t)" {
start
	:object_it = find(object_number);
	if (object_it != end() && *object_it が xref_inuse_entry && object_it->generation_number == generation_number) then (y)
		:return object_it;
		stop
	else
		:return end();
		stop
	endif
}
@enduml
