@startuml ipdfstream
hide empty members
namespace pdfparser {
class ipdfstream {
	+ipdfstream(inout sb : std::streambuf*)

	+take_footer() : dictionary_object
	+take_xref_table() : xref_table
	+take_xref_entry(in object_number : object_t) : xref_entry
	+take_trailer() : dictionary_object
}
ipdfstream --|> object_stream
ipdfstream ..> xref_types
ipdfstream ..> object_types
ipdfstream ..> parse_error


class object_stream {
	[[object_stream.class.pu]]
}
annotation xref_types <<(N, yellow) namespace>> {
	[[xref_types.class.pu]]
}
annotation object_types <<(N, yellow) namespace>> {
	[[object_types.class.pu]]
}
class parse_error {
	[[parse_error.class.pu]]
}
}
@enduml
