@startuml pdfpage_builder
hide empty members
class pdfpage_builder {
	+pdfpage_builder()
	+toPDFPage() : PDFPage
	+SetMediaBox(media_box : const RectangleData&)
	+SetContents(page_content : const PDFContents&)
	-m_page : PDFPage
}
pdfpage_builder --|> pdfcontents_builder
pdfpage_builder --> PDFPage
pdfpage_builder --> graphics_state

abstract pdfcontents_builder {
	[[pdfcontents_builder.class.pu]]
}
class PDFPage {
	[[PDFPage.class.pu]]
}
class graphics_state {
	[[graphics_state.class.pu]]
}
@enduml
