@startuml space
hide empty members
namespace pdfparser::space {
class Coordinates {
	+x : double
	+y : double
}
class RectangleData<<struct>> {
	+less_coordinates    : Coordinates
	+greater_coordinates : Coordinates

	+RectangleData(diagonal_coordinate1 : Coordinates, diagonal_coordinate2 : Coordinates)
}
class AffineMatrix {
}
AffineMatrix --|> Matrix3d
}
@enduml
