@startuml portion_of_stream
hide empty members
namespace pdfparser {
abstract portion_of_stream {
	-m_position : optional<std::streampos>

	+portion_of_stream(position : optional<std::streampos>)

	+position() : std::streampos
}
}
@enduml
