@startuml promise_token_failed
partition "promise_token_failed<InputIterator>(in position : std::streampos, in first : InputIterator, in last : InputIterator)" {
start
	:message : stringstream;
	:message << "以下のいずれかのトークンを期待しましたが、いずれも取得できませんでした。\\n";

	while (promise_token_str in [first, last)) is (y)
		:message << promise_token_str;
		:message << " (";
		:old_flags = message.setf(std::ios_base::hex | std::ios_base::uppercase);
		while (character in promise_token_str) is (y)
			:message << static_cast<unsigned int>(character);
		endwhile
		:message.flags(old_flags);
		:message << ")";
		:message << '\\n';
	endwhile

	:position_indicatable_error(position, message.str());
stop
}
@enduml
