@startuml tokenizer_errors
hide empty members
namespace pdfparser {
class promise_token_failed {
	-m_promise_token_list : forward_list<string>
	+promise_token_failed(in offset_from_stream_head, in promise_token_list : forward_list<string>)
	+detail() : string
}
promise_token_failed ..|> position_indicatable_error

interface document_error {
	+what() : string
}
}
@enduml
