@startuml failed_to_get
partition "detail()" {
start
	:return "次の文字の取得に失敗しました。";
stop
}
@enduml

@startuml failed_to_seek_what
partition "detail()" {
start
	:return m_seekpos + "バイト目にシーク出来ませんでした。";
stop
}
@enduml

@startuml failed_to_seek_forward_head_of_line
partition "detail()" {
start
	:return "前の行にシーク出来ませんでした。";
stop
}
@enduml

@startuml promise_failed_what
partition "detail()" {
start
	:message : stringstream;
	:message << "以下の文字列のいずれかの文字列を期待しましたが、いずれも取得できませんでした。\\n";

	while (promise_str in m_promise_list) is (y)
		:message << promise_str;
		:message << " (";
		:old_flags = message.setf(std::ios_base::hex | std::ios_base::uppercase);
		while (character in promise_str) is (y)
			:message << static_cast<unsigned int>(character);
		endwhile
		:message.flags(old_flags);
		:message << ")";
		:message << '\\n';
	endwhile

	:return message.str();
stop
}
@enduml
