@startuml ipdfstream
hide empty members
namespace pdfparser {
enum istream_extended_error::error_code <<Enumeration>> {
	<<Const>>
	+{static} failed_to_seek                      : int = 0
	+{static} failed_to_seek_forward_head_of_line : int = 1
	+{static} promise_failed                      : int = 2
}

class istream_extended_error {
	+enum error_code
	-m_error_code : const error_code

	+istream_extended_error(in er_code : error_code)
	+code() : error_code
}
istream_extended_error --|> std::runtime_error
istream_extended_error --> "1" istream_extended_error::error_code
}
@enduml
