@startuml istream_extended_errors
hide empty members
namespace pdfparser {
class failed_to_get {
	+detail() : string
}
failed_to_get ..|> position_indicatable_error

class failed_to_seek {
	-m_seekpos : std::streamoff
	+failed_to_seek(seekpos : std::streamoff)
	+what() : string
}
failed_to_seek ..|> document_error

class failed_to_seek_forward_head_of_line {
	+detail() : string
}
failed_to_seek_forward_head_of_line ..|> position_indicatable_error

class promise_failed {
	-m_promise_list : forward_list<string>
	+promise_failed(in offset_from_stream_head : std::streamoff, in promise_list : forward_list<string>)
	+detail() : string
}
promise_failed ..|> position_indicatable_error

interface document_error {}
abstract position_indicatable_error {}
position_indicatable_error ..|> document_error
}
@enduml
