@startuml contains
partition "contains(in object_id : const pair<object_t, generation_t>&)" {
start
	:return m_object_map.contains(object_id);
stop
}
@enduml

@startuml get
partition "get(in object_id : const pair<object_t, generation_t>&)" {
start
	:return m_object_map.at(object_id);
stop
}
@enduml

@startuml add
partition "add(in object_id : pair<object_t, generation_t>, in object : any_direct_object)" {
start
	:m_object_map.emplace(object_id, object);
stop
}
@enduml
