@startuml object_pool
hide empty members
namespace pdfparser {
class object_pool {
	-m_object_map : unordered_map<pair<object_t, generation_t>, any_direct_object>

	+object_pool()
	+contains(in object_id : const pair<object_t, generation_t>&) : bool
	+get(in object_id : const pair<object_t, generation_t>&) : const any_direct_object&
	+add(in object_id : pair<object_t, generation_t>, in object : any_direct_object)
}
object_pool --> object_types

annotation object_types <<(N, yellow) namespace>> {
	[[object_types.class.pu]]
}
}
@enduml
