@startuml graphics_state_stack
partition "graphics_state_stack()" {
start
	:m_graphics_states.emplace();
stop
}
@enduml

@startuml store_graphics_state
partition "store_graphics_state()" {
start
	:m_graphics_states.push(m_graphics_states.top());
stop
}
@enduml

@startuml restore_graphics_state
partition "restore_graphics_state()" {
start
	:m_graphics_states.pop();
stop
}
@enduml

@startuml current_graphics_state
partition "current_graphics_state()" {
start
	:m_graphics_states.top();
stop
}
@enduml
