@startuml graphics_state
hide empty members
namespace pdfparser {
class graphics_state {
	% general parameters
	+clipping_path : 
	+current_transformation_matrix : AffineMatrix
	+current_point : coordinates
	+fill_color : chroma::color
	+flatness : double
	+line_cap_style    : line_style::cap_type
	+line_dash_pattern : line_style::dash_pattern_type
	+line_join_style   : line_style::join_type
	+line_width : double
	+miter_limit : double
	+stroke_color : chroma::color

	% text-specific parameters
	+character_spacing : double
	+horizontal_scaling : double
	+leading : double
	+text_font : 
	+text_rise : double
	+text_size : double
	+text_rendering_mode : text_style::rendering_mode
	+word_spacing : double

	+graphics_state()
}
graphics_state --> AffineMatrix
graphics_state --> coordinates
graphics_state --> chroma::color
graphics_state --> line_style::cap_type
graphics_state --> line_style::dash_pattern_type
graphics_state --> line_style::join_type
graphics_state --> text_style::rendering_mode

class AffineMatrix {
	[[space.class.pu]]
}
class coordinates {
	[[space.class.pu]]
}

class chroma::color {
	[[chroma.class.pu]]
}

enum line_style::cap_type {
	[[line_style.class.pu]]
}
class line_style::dash_pattern_type {
	[[line_style.class.pu]]
}
enum line_style::join_type {
	[[line_style.class.pu]]
}

enum text_style::rendering_mode {
	[[text_style.class.pu]]
}
}
@enduml
