@startuml object_cache
hide empty members
namespace pdfparser {
class object_cache {
	-m_object_map : unordered_map<pair<object_t, generation_t>, any_direct_object>

	+object_cache()
	+contains(in object_id : const pair<object_t, generation_t>&) : bool
	+get(in object_id : const pair<object_t, generation_t>&) : const any_direct_object&
	+add(in object_id : pair<object_t, generation_t>, in object : any_direct_object) : void
}
object_cache --> object_types

annotation object_types <<(N, yellow) namespace>> {
	[[object_types.class.pu]]
}
}
@enduml
