@startuml object_types_errors
hide empty members
namespace pdfparser {
class type_mismatch {}
type_mismatch ..|> document_error

class onstream_type_mismatch {}
onstream_type_mismatch ..|> position_indicatable_error

class integer_object_overflows {}
integer_object_overflows ..|> document_error

class onstream_integer_object_overflows {}
onstream_integer_object_overflows ..|> position_indicatable_error

abstract position_indicatable_error {}
interface document_error {}
document_error ..|> position_indicatable_error
}
@enduml
