@startuml parser
hide empty members
namespace pdfparser {
class footer <<struct>> {
	+xref_byte_offset : std::streamoff
	+xref_table : xref_table

	+footer(inout istr : std::istream&)
}
footer x..> syntax_error
footer x..> parser_utility
footer "1" x--> "1" xref_table

class syntax_error {
	[[error_types.class.pu]]
}
annotation parser_utility <<(N, yellow) unnamed namespace>> {
	[[parser_utility.class.pu]]
}
class xref_table {
	[[xref_types.class.pu]]
}
}
@enduml
