@startuml footer
partition "footer(inout istr : std::istream&)" {
start
	:istr を最終行の行頭に移動;
	if (移動できなかった) then (y)
		:throw syntax_error(keyword_EOF_not_found);
		stop
	endif
	:require(istr, keyword_EOF);
	:istr を最終行の1行前の行頭に移動;
	if (移動できなかった) then (y)
		:throw syntax_error(xref_byte_offset_not_found);
		stop
	endif
	:xref_byte_offset = take_xref_byte_offset(istr);
	:istr を最終行の2行前の行頭に移動;
	if (移動できなかった) then (y)
		:throw syntax_error(keyword_startxref_not_found);
		stop
	endif
	:require(istr, keyword_startxref);

	:istr を先頭から m_xref_byte_offset バイト目に移動;
	:xref_table = take_xref_table(istr);
stop
}
@enduml
