@startuml overview
hide empty members
class document_reader {}
document_reader *--> page_tree_parser
document_reader o--> ipdfstream

class page_tree_parser {}
page_tree_parser *--> page_parser
page_tree_parser o--> ipdfstream

class page_parser {}
page_parser *--> contents_parser
page_parser o--> ipdfstream

class contents_parser {}
contents_parser o--> ipdfstream


' PDF入力ストリーム
class ipdffstream {
	PDFファイルストリーム
}
ipdffstream --|> ipdfstream
ipdffstream --|> std::ifstream

std::ifstream --|> std::istream

class ipdfstringstream {
	PDF文字列ストリーム
}
ipdfstringstream --|> ipdfstream
ipdfstringstream --|> std::istringstream

std::istringstream --|> std::istream

class ipdfstream {
}
ipdfstream *-- object_cache
ipdfstream --|> object_stream

class object_cache {
	間接オブジェクトのキャッシュ
}

class object_stream {
	PDFオブジェクト取得
}
object_stream --|> tokenizer

class tokenizer {
	トークン取得
}
tokenizer --|> istream_extended

istream_extended --|> std::istream
@enduml
