@startuml parser
partition "parser(in stream : InputStreamT&&)" {
start
	:m_stream_parser = stream_parser(std::move(stream));
	:m_object_pool = object_pool(m_stream_parser);
	:m_trailer_dictionary = m_stream_parser.take_footer(m_object_pool);
stop
}
@enduml
