@startuml PDFPage
hide empty members
class PDFPage<<struct>> {
	+MediaBox : RectangleData
	+Contents : PDFContents

	+PDFPage()
}
PDFPage --> RectangleData
PDFPage --> PDFContents

class RectangleData {
	[[data_types.class.pu]]
}
class PDFContents {
	[[PDFContents.class.pu]]
}

@enduml
