@startuml tokenize_error
hide empty members
namespace pdfparser {
enum tokenize_error::error_code <<Enumeration>> {
	<<Const>>
	+{static} promise_token_failed : int = 0
}
class tokenize_error {
	+enum error_code
	-m_error_code : const error_code

	+tokenize_error(in er_code : error_code)
	+code() : error_code
}
tokenize_error --|> std::runtime_error
tokenize_error --> "1" tokenize_error::error_code
}
@enduml
