@startuml graphics_state_manager
hide empty members
abstract graphics_state_manager {
	+graphics_state_manager()
	+store_graphics_state()   : void
	+restore_graphics_state() : void
	#current_graphics_state() : graphics_state&
	-m_graphics_states : stack<graphics_state>
}
graphics_state_manager --> "*" graphics_state
@enduml
