@startuml text_style
hide empty members
namespace pdfparser::text_style {
enum rendering_mode {
	<<Const>>
	+{static} fill                  = 0
	+{static} stroke                = 1
	+{static} fill_and_stroke       = 2
	+{static} no_fill_and_no_stroke = 3
}
}
@enduml
