@startuml document_parser
hide empty members
namespace pdfparser {
enum whitespace_flags <<Enumeration>> {
	<<Const, Flag>>
	+{static} none            : uint8_t = 0
	+{static} null            : uint8_t = 1
	+{static} horizontal_tab  : uint8_t = 2
	+{static} line_feed       : uint8_t = 4
	+{static} form_feed       : uint8_t = 8
	+{static} carriage_return : uint8_t = 16
	+{static} space           : uint8_t = 32
	+{static} comment         : uint8_t = 64

	+{static} EOL
	 : uint8_t = line_feed | carriage_return
	+{static} any_whitespace_characters
	 : uint8_t = null | horizontal_tab | line_feed | form_feed | carriage_return | space | EOL
	+{static} any_whitespace_characters_except_EOL
	 : uint8_t = any_whitespace_characters & ~EOL
}
}
@enduml
