@startuml page_parser
hide empty members
namespace pdfparser {
class page_parser<InputStreamT> {
	-m_object_pool   : object_pool<InputStreamT>&
	-m_page_object   : const dictionary_object&

	+page_parser(obj_pool : object_pool<InputStreamT>&, page_object : const dictionary_object&)
	+get_page() : PDFPage
}
page_parser ..> object_pool
page_parser ..> dictionary_object
page_parser ..> PDFPage

class object_pool {
	[[object_pool.class.pu]]
}
class dictionary_object {
	[[object_types.class.pu]]
}
class PDFPage {
	[[PDFPage.class.pu]]
}
@enduml
