@startuml page_parser
hide empty members
namespace pdfparser {
class page_parser<InputStreamT> {
	-m_object_parser : object_parser<InputStreamT>&
	-m_page_object     : const dictionary_object&

	+page_parser(obj_parser : object_parser<InputStreamT>&, page_object : const dictionary_object&)
	+get_page() : PDFPage
}
page_parser ..> object_parser
page_parser ..> dictionary_object
page_parser ..> PDFPage

class object_parser {
	[[object_parser.class.pu]]
}
class dictionary_object {
	[[object_types.class.pu]]
}
class PDFPage {
	[[PDFPage.class.pu]]
}
@enduml
