@startuml contents_parser
hide empty members
namespace pdfparser {
class contents_parser<InputStreamT> {
	-m_ipdfstream : ipdfstream<InputStreamT>&

	+contents_parser(obj_parser : ipdfstream<InputStreamT>&)
	+get_contents() : PDFContents
}
contents_parser ..> ipdfstream
contents_parser ..> PDFContents

class ipdfstream<InputStreamT> {
	[[ipdfstream.class.pu]]
}
class PDFContents {
	[[PDFContents.class.pu]]
}
@enduml
