@startuml contents_parser
hide empty members
namespace pdfparser {
class contents_parser {
	-m_content_stream : ipdfstream&

	+contents_parser(content_stream : ipdfstream&)
	+get_contents() : PDFContents
}
contents_parser ..> ipdfstream
contents_parser ..> PDFContents

class ipdfstream {
	[[ipdfstream.class.pu]]
}
class PDFContents {
	[[PDFContents.class.pu]]
}
@enduml
